#!/bin/sh -e
# vim: fdm=marker

# Read Arguments & Environment {{{

if [ ${#@} -ne 0 ]; then
  case $* in
    *--help*) printf -- '...help...\n'; exit 0;;
    *-h*) printf -- '...help...\n'; exit 0;;
  esac

  case $* in
    *--quiet*) quiet="true";;
    *-q*) quiet="true";;
  esac
fi

# }}}

# Functions {{{

function echoq {
  if [ ! -n "$quiet" ]; then
    echo $*
  fi
}

function check_network {
  if ping -q -c 1 -W 1 1.1.1.1 >/dev/null; then
    echoq '--> We are online!'
  else
    echoq '--> Network not established, exiting early..'
  fi
}

function check_command {
  if [ ! $(command -v $1) ]; then
    printf -- "You don't seem to have $1 installed.\n"
    exit 127
  # else
  #  echoq "$1 is installed."
  fi
}

# }}}

echoq 'Rollout'

# Basics
# Minimal configuration that needs no internet connection
# Tools/PATH {{{

echoq '--> Do I have the basics?'

check_command grep
check_command 'vim'
check_command 'nvim'
check_command 'tmux'
# check_command 'screen' # todo this should be conditional

# }}}

# Locale.. things like LANG/keyboard setting caps as ctrl
# What should that be called? I guess this is the place to put most shellrc stuff
# Locale {{{

echoq '--> What is my current keyboard layout?'
echoq 'where should I write thing config to?'
echoq "echoq 'setxkbmap us etc > /etc/.bashrc'? "
echoq '--> what is my timezone?'
echoq '--> is there a time sync daemon?'
echoq '--> am I inside docker? no init?'

if [ ! $(command -v /bin/bash) ]; then
  echoq '!!! bash is not available'
  exit 1
fi

# TODO check arch linux for general recommendations

# }}}

# Have you considered, the aesthetics? {{{

echoq '--> inside X'
echoq '--> inside regular console'
# set ter-228b
# write to /etc/vconsole.conf
echoq '--> hidpi'
# write to .xinitrc

echoq '--> if openbox-session is available.. what's the fallback?

# }}}

echoq '--> Is rollout or bin file on path?'


echoq '--> Is git configured?'
echoq 'what do I want to be there?'
echoq 'aa + ci + maybe ra?'

echoq '--> Do I have an ssh key?'
echoq '--> Is systemd running?'
echoq '--> Is ssh-agent running?'

# Colors {{{

echoq 'choose night or day'

# take vars describes here, put them into their respective configs

# TODO should be if --sun/--moon/--lumo etc (lumo by default for now)
if true; then
  echoq 'Sun theme'
# # Sun theme
# *.foreground:   #fcfcfa
# *.background:   #2d2a2e
# *.cursorColor:  #fcfcfa
# 
# ! black
# *.color0:       #383539
# *.color8:       #989599
# 
# ! red
# *.color1:       #ff6188
# *.color9:       #ff89a6
# 
# ! green
# *.color2:       #a9dc76
# *.color10:      #c5e0a9
# 
# ! yellow
# *.color3:       #fc9867
# *.color11:      #ffd866
# 
# ! blue
# *.color4:       #78dce8
# *.color12:      #c9edf1
# 
# ! magenta
# *.color5:       #ab9df2
# *.color13:      #b294bb
# 
# ! cyan
# *.color6:       #78e8cf
# *.color14:      #c4f9ed
# 
# ! white
# *.color7:       #c3c1c3
# *.color15:      #f8f8f2
fi


echoq '--> Does my shell have colors set?'
echoq '--> for X?'
echoq '--> for OSX?'
echoq '--> for Cygwin?'
echoq '--> for Powershell?'
echoq '--> for (neo)vim?'
echoq '--> for emacs?'

# }}}

check_network

echoq '--> Has git?'
echoq '--> Maven?'
echoq '--> openjdk 11 and src?'
echoq '--> Has clojure/clj?'
echoq '--> Has lein?'
echoq '--> Has boot?'
echoq '--> Has gimp?'
echoq '--> terminus -- good default you can rely on?'

# Nice to have {{{

echoq '--> Has rlwrap'

# }}}

# if --all-languages is selected try to install everything
echoq '--> Has go?'
echoq '--> Has haskell?'
echoq '--> Has ruby?'
echoq '--> Has node?'
echoq '--> Has python?'
echoq '--> Has gcc?'
echoq '--> Has rust?'

echoq '--> Hugo for blogs? or something different?'
echoq '--> darkroom? gthumb? --extra? --full?'

# Technologies {{{
echoq '--> Has postgresql?'
echoq '--> Has redis?'
# }}}

# Window Management + everyday utils {{{

echoq '--> scrot/screenshot util'
echoq '--> slock'
echoq '--> openbox?'
echoq '--> in osx/windows are there any helpers?'

# }}}

# Design decisions
#
# Should rollout have softlinked files?
# Copy files stored inside a single sh file?
# echo minimal config?
#
# How destructive can rollout be? Could I use it on someone else's computer with confidence?
# maybe just mv to old if found? create new.. diff if diff then write over old
#
# Log what happened?
#
# How can I make output look pretty?
#
# # How do I source missing binaries?
# -> by package manager? select only a few supported platforms? e.g arch? nix?
