#!/bin/bash -e

join_by() { local IFS="$1"; shift; echo "$*"; }

# started for pi 4

packages=(
neovim
xterm
tmux # terminal multiplexer
openbox # X11 window manager
xinit
gimp # photo editor
feh # image utility view images/display backgrounds etc
tint2 # taskbar/panel
fonts-ubuntu
)

sudo apt-get install -y $(join_by ' ' "${packages[@]}")

sudo systemctl enable ssh # enable sshd at boot

# TODO include openbox config

function rpi4_config {
  # TODO how is lakka more performant in retroarch/emulation?
  # TODO how does lakka pick up n64 games that raspbian install did not?
  # -> review cores
  # -> review lakka docs
  # -> review lakka retroarch.cfg

  # TODO check if we need to update pi firmware

  # TODO get a n64 game working on raspbian to test performance..

  # TODO retroarch options:
  # -> best video driver? gl/glcore (crashes on videocore)
  # -> threaded video? false
  # -> vsync? false (not available on pi anyway..)
  # -> bilinear filtering? false
  # -> audio_driver? alsathread
  # -> rewind_enable? = false
  # XXX Reference: https://www.raspberrypi.org/documentation/configuration/config-txt/
  # XXX Reference: https://github.com/sakaki-/gentoo-on-rpi-64bit#miscellaneous-configuration-notes-hints-and-tips-skip
  # XXX Reference: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=243500&p=1490467#p1490467
  return 1
}

function retroarch_install {
  sudo apt-get install \
    libxxf86vm-dev \
    libxxf86dga-dev \
    libx11-xcb-dev \
    libavdevice-dev \
    libgles2-mesa-dev \
    xorg-dev

    # Edit Makefile and add a line: UDEV_LIBS += -lXxf86vm
    CFLAGS='-mfpu=neon -mtune=cortex-a72 -march=armv8-a' ./configure --disable-opengl1 --enable-neon --enable-opengles3 --enable-opengles --disable-videocore
    make -j4
}
