#!/bin/bash -e

# Set the keyboard permanently to US w/ ctrl as caps:
sudo sed -i \
  -e 's/XKBLAYOUT=\"\w*"/XKBLAYOUT=\"us\"/g' \
  -e 's/XKBOPTIONS=\"\w*"/XKBOPTIONS=\"ctrl:nocaps\"/g' \
  /etc/default/keyboard


# TODO should probably update too..
sudo apt install -y \
  curl \
  tmux \
  vim-gtk3 \
  build-essential \
  apt-file

# Install the latest Node LTS:
if ! command -v node; then
  curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
  # TODO something weird happened when doing this manually:
  # - initially I had no npm
  # - .. did some stuff (maybe sudo apt-get update?)
  # - sudo apt-get install nodejs provided npm (althought sudo apt-get install
  #   npm ubuntu package still could not resolve it's dependencies')
  sudo apt-get install -y nodejs

  # give yourself write permissions for node modules
  sudo mkdir -p /usr/lib/node_modules
  sudo chown -R $USER /usr/lib/node_modules
fi

# TODO hide firefox titlebar by script (currently change via customize menu item => checkbox)
